name: Run indradia.py manually

on:
  workflow_dispatch:  # this is required for manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
           pip install pandas_ta yfinance vaderSentiment transformers torch feedparser
           
      - name: Run the script
        run: python indradia.py
