name: Run Cerbero Notebook Daily

# Trigger: daily at 7 AM UTC and manual runs
on:
  schedule:
    - cron: '0 7 * * *'  # every day at 07:00 UTC
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: List repo files to debug paths
      - name: List repo files
        run: ls -R

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 4: Install dependencies including nbconvert
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ta jupyter nltk
          pip install nbconvert yfinance vaderSentiment transformers torch feedparser

      # Step 5: Convert notebook to Python script
      - name: Convert notebook to script
        run: |
          jupyter nbconvert --to script cerbero.ipynb --output cerbero
          mv cerbero.txt cerbero.py || true

      # Step 6: Confirm the Python script exists
      - name: Confirm Python script exists
        run: ls -l cerbero.py

      # Step 7: Show first 5 lines of the script
      - name: Show first 5 lines
        run: head -n 5 cerbero.py

      # Step 8: Run the generated Python script
      - name: Run the script
        run: python cerbero.py


      # Step 7: Commit and push updated data files
      - name: Commit and push updated data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git add *_datos.txt
          git diff --cached --quiet || git commit -m "Update generated data files"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/4L3M4R/cerbero.git HEAD:main



          
