name: Run Cerbero Notebook Daily

on:
  schedule:
    - cron: '0 11 * * *'  # 7:00 AM EDT
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ta jupyter nltk
          pip install nbconvert yfinance vaderSentiment transformers torch feedparser

      # Step 4: Backup existing data files BEFORE running the script
      - name: Backup existing data files
        run: |
          mkdir -p /tmp/generated
          mkdir -p /tmp/backup
          shopt -s nullglob
          timestamp=$(date +%Y%m%d%H%M%S)
          for f in *_datos.txt; do
              echo "Backing up $f..."
              cp "$f" "/tmp/generated/$f"
              cp "$f" "/tmp/backup/${f%.txt}_backup_${timestamp}.txt"
          done
          echo "Contents of /tmp/generated:"
          ls -l /tmp/generated || echo "No generated files"
          echo "Contents of /tmp/backup:"
          ls -l /tmp/backup || echo "No backups found"

      # Step 5: Convert notebook to Python script
      - name: Convert notebook to script
        run: |
          jupyter nbconvert --to script cerbero.ipynb --output cerbero
          mv cerbero.txt cerbero.py || true

      # Step 6: Run the script (generates new lines / updates)
      - name: Run the script
        run: python cerbero.py

      # Step 7: Restore backup files into repo folder
      - name: Restore backup files to repo
        run: |
          mkdir -p backup
          cp /tmp/generated/*_datos.txt . 2>/dev/null || echo "No data files restored"
          cp /tmp/backup/* backup/ 2>/dev/null || echo "No backup files restored"
          echo "Restored data files:"
          ls -l *_datos.txt || echo "No restored data files"
          echo "Restored backup folder contents:"
          ls -l backup || echo "No backup files"

      # Step 8: Commit and push all updates (new data + backup)
      - name: Commit and push updates
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
      
          echo "Preparing to commit:"
          ls -l *_datos.txt backup || echo "No files to commit"
      
          git add *_datos.txt backup/ || echo "Nothing to add"
      
          # ← Aquí agregarías los logs nuevos:
          git add logs/*_descargadas_*.csv logs/*_nuevas_agregadas_*.csv
          git add logs/log_resumen.txt || echo "No logs to add"
      
          git diff --cached --quiet || git commit -m "Update generated data, backups and logs" || true

          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/4L3M4R/cerbero.git
          git push origin HEAD:main

      # Optional: show last commit
      - name: Show last commit
        run: git log -1 --stat
